---
title: "Plots"
author: "aaron till"
date: "4/19/2018"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(stringr)
library(plyr)
```


# Data Import
```{r}

Affordable_Housing_10_14 <- read.csv("HAI_map_2010-14.csv")  %>%
  mutate(countyname2 = str_remove(countyname, pattern = ' County')) 


Affordable_Housing_05_09 <- read.csv("HAI_map_2005-09.csv")  %>%
  mutate(countyname2 = str_remove(countyname, pattern = ' County')) 


Evictions <- read_xlsx('eviction_lab_export.xlsx')

Oregon_Housing_Prices <- read_xlsx('2017-OOR-OR.xlsx')



PIT_State <- read_xlsx("2007-2017-PIT-Counts-by-State.xlsx")

Helper_State_Abrvs <- read.csv("states.csv.csv")

```


#PIT COC - Expanding years

```{r}



PIT_CoC_2017 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 1)
PIT_CoC_2016 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 2)
PIT_CoC_2015 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 3)
PIT_CoC_2014 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 4)
PIT_CoC_2013 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 5)
PIT_CoC_2012 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 6)
PIT_CoC_2011 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 7)
PIT_CoC_2010 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 8)
PIT_CoC_2009 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 9)
PIT_CoC_2008 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 10)
PIT_CoC_2007 <- read_xlsx("2007-2017-PIT-Counts-by-CoC.XLSX.xlsx", sheet = 11)

PIT_CoC <- join_all(list(PIT_CoC_2007, PIT_CoC_2008, PIT_CoC_2009, PIT_CoC_2010, PIT_CoC_2011, PIT_CoC_2012, PIT_CoC_2013, PIT_CoC_2014, PIT_CoC_2015, PIT_CoC_2016, PIT_CoC_2017))

PIT_CoC <- PIT_CoC %>%
  dplyr::rename('CoC_Name' = 'CoC Name') %>% #dplyr:: neccesary because plyr analog
  dplyr::rename('Unsheltered_2017' =  'Unsheltered Homeless, 2017' )%>%
  dplyr::rename('Total_Homeless_2017' = 'Homeless Individuals, 2017') %>%
  dplyr::rename('Unsheltered_2016' =  'Unsheltered Homeless, 2016' )%>%
  dplyr::rename('Total_Homeless_2016' = 'Homeless Individuals, 2016') %>%
  dplyr::rename('Unsheltered_2015' =  'Unsheltered Homeless, 2015' )%>%
  dplyr::rename('Total_Homeless_2015' = 'Homeless Individuals, 2015') %>%
  dplyr::rename('Unsheltered_2014' =  'Unsheltered Homeless, 2014' )%>%
  dplyr::rename('Total_Homeless_2014' = 'Homeless Individuals, 2014') %>%
  dplyr::rename('Unsheltered_2013' =  'Unsheltered Homeless, 2013' )%>%
  dplyr::rename('Total_Homeless_2013' = 'Homeless Individuals, 2013') %>%
  dplyr::rename('Unsheltered_2012' =  'Unsheltered Homeless, 2012' )%>%
  dplyr::rename('Total_Homeless_2012' = 'Homeless Individuals, 2012') %>%
  dplyr::rename('Unsheltered_2011' =  'Unsheltered Homeless, 2011' )%>%
  dplyr::rename('Total_Homeless_2011' = 'Homeless Individuals, 2011') %>%
  dplyr::rename('Unsheltered_2010' =  'Unsheltered Homeless, 2010' )%>%
  dplyr::rename('Total_Homeless_2010' = 'Homeless Individuals, 2010') %>%
  dplyr::rename('Unsheltered_2009' =  'Unsheltered Homeless, 2009' )%>%
  dplyr::rename('Total_Homeless_2009' = 'Homeless Individuals, 2009') %>%
  dplyr::rename('Unsheltered_2008' =  'Unsheltered Homeless, 2008' )%>%
  dplyr::rename('Total_Homeless_2008' = 'Homeless Individuals, 2008') %>%
  dplyr::rename('Unsheltered_2007' =  'Unsheltered Homeless, 2007' )%>%
  dplyr::rename('Total_Homeless_2007' = 'Homeless Individuals, 2007') %>%
  mutate(countyname2 = str_remove(CoC_Name, pattern = ' CoC'))  # INCORPORATED REGIONS NOT COUNTIES 







```

# County Tidying of Affordable Housing - Oregon Only
```{r}

Affordable_Housing_10_14_Oregon <- Affordable_Housing_10_14 %>%
  filter(State_Name == 'Oregon') %>%
  filter(!is.na(Total))

Affordable_Housing_10_14_Oregon$Area <- Affordable_Housing_10_14_Oregon$countyname2

Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Hood River')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Jefferson')] <- 'Central_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Crook')] <- 'Central_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Tillamook')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Curry')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Wasco')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Columbia')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Malheur')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Union')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Clatsop')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Lincoln')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Umatilla')] <- 'Rural_Oreogn'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Coos')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Polk')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Yamhill')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Klamath')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Josephine')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Douglas')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Linn')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Deschutes')] <- 'Central_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Benton')] <- 'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Jackson')] <- 'Jackson'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Clackamas')] <- 'Clackamas'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Marion')] <-'Rural_Oregon'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Washington')] <- 'Washington'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Lane')] <- 'Lane'
Affordable_Housing_10_14_Oregon$Area[which(Affordable_Housing_10_14_Oregon$countyname2 == 'Multnomah')] <- 'Multnomah' 


Affordable_Housing_10_14_Oregon <- Affordable_Housing_10_14_Oregon %>%
  group_by(Area) %>%
  dplyr::summarise(units = mean(units), per100 = mean(per100)) # also must specify dplyr

```

#County tidying of PIT - Oregon Only 
```{r}

PIT_CoC_Oregon<- PIT_CoC %>%
  filter(countyname2 == 'Eugene/Springfield/Lane County'| countyname2 == 'Portland-Gresham-Multnomah County'| countyname2 == 'Medford/Ashland/Jackson County'| countyname2 == 'Central Oregon'| countyname2 == 'Oregon Balance of State'| countyname2 == 'Hillsboro/Beaverton/Washington County'| countyname2 == 'Clackamas County') 


PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Eugene/Springfield/Lane County')] <- 'Lane'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Portland-Gresham-Multnomah County')] <- 'Multnomah'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Medford/Ashland/Jackson County')] <- 'Jackson'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Central Oregon')] <- 'Central_Oregon'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Oregon Balance of State')] <- 'Rural_Oregon'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Hillsboro/Beaverton/Washington')] <- 'Washington'
PIT_CoC_Oregon$Area[which(PIT_CoC_Oregon$countyname2 =='Clackamas County')] <- 'Clackamas'




PIT_Housing_Oregon_Merge <- merge(Affordable_Housing_10_14_Oregon, PIT_CoC_Oregon)



```

```{r}
ggplot(PIT_Housing_Oregon_Merge, aes(x = Unsheltered_2017, y = per100, label = Area)) +
  geom_point()+
  geom_text()


```





# State Tidying
```{r}
 
Affordable_Housing_10_14_State <- Affordable_Housing_10_14 %>%
  group_by(State_Name) %>%
  dplyr::summarise(units = mean(units, na.rm = TRUE), per100 = mean(per100, na.rm = TRUE))

Intermediate_Housing_State_Abrvs <-full_join(Affordable_Housing_10_14_State, Helper_State_Abrvs, by = c('State_Name' = 'State'))

PIT_Housing_State_Merge <- inner_join(Intermediate_Housing_State_Abrvs, PIT_State, by = c('Abbreviation' = 'state')) %>%
  dplyr::rename('Change_2007' = 'Change in Total Homelessness, 2007-2017') %>%
  dplyr::rename('Change_2008' = 'Change in Total Homelessness, 2008-2017') %>%
  dplyr::rename('Change_2009' = 'Change in Total Homelessness, 2009-2017') %>%
  dplyr::rename('Change_2010' = 'Change in Total Homelessness, 2010-2017') %>%
  dplyr::rename('Change_2011' = 'Change in Total Homelessness, 2011-2017') %>%
  dplyr::rename('Change_2012' = 'Change in Total Homelessness, 2012-2017') %>%
  dplyr::rename('Change_2013' = 'Change in Total Homelessness, 2013-2017') %>%
  dplyr::rename('Change_2014' = 'Change in Total Homelessness, 2014-2017') %>%
  dplyr::rename('Change_2015' = 'Change in Total Homelessness, 2015-2017') %>%
  dplyr::rename('Change_2016' = 'Change in Total Homelessness, 2016-2017') 



```

```{r}



ggplot(PIT_Housing_State_Merge, aes(y = as.numeric(Change_2014), x = per100)) +
  geom_point() + 
  geom_smooth(method = 'lm')

```
