---
title: "Project Proposal"
author: "best-team"
date: "3/27/2018"
output: github_document
---

# Project Proposal

## General theme that you wish you address:
  
1. How does spending affect homelessness? 

## Specific questions you may address along with your expectation of what you may find:

1. Which programs are better? 
2. What factors contribute to chronic homelessness? (race gender sexuality stuff, spending, disabled, veteran, how long someone has been,  etc to check if someone will stay homeless)
 

## Unit of observation:

1. Individual, if possible.
2. County level.
3. City level. 
  


## Relevant work:
https://slack-redir.net/link?url=http%3A%2F%2Fjournals.sagepub.com%2Fdoi%2Fabs%2F10.2307%2F1389580
http://journals.sagepub.com/doi/abs/10.1177/004208169102700109
http://nlihc.org/sites/default/files/Patchwork-2001.pdf
http://nlihc.org/library/preservation
http://ajph.aphapublications.org/doi/abs/10.2105/AJPH.2005.063321
https://slack-redir.net/link?url=https%3A%2F%2Fonlinelibrary.wiley.com%2Fdoi%2Ffull%2F10.1002%2F1520-6629%2528199407%252922%253A3%253C272%253A%253AAID-JCOP2290220307%253E3.0.CO%253B2-X


## Client/stakeholders and their contact information:

Antoinette Pietka, Bimal Rajbahandary, Anna Plumb, 
other possible contacts  - https://www.portlandoregon.gov/inr_view.cfm?id=241 , http://nlihc.org/involvement/local/state/OR 


## Possible Data Sources: 

https://www.huduser.gov/portal/datasets/cp.html#2006-2014_data
http://nlihc.org/library/research
https://slack-redir.net/link?url=http%3A%2F%2Fwww.csh.org%2Fwp-content%2Fuploads%2F2013%2F08%2FEstimating-the-Need.pdf
https://public.tableau.com/profile/oregon.housing.and.community.services#!/vizhome/InformationDashboardPITCount_1/Point-in-TimeCount
the excel stuff on Ryan's computer


## Things to check

1. Percentage of people who arrived recently (individual level)
2. Reoccurence in multiple years (individual level)
3. Relationship of housing prices and minimum wage to homelessness.
4. The interaction of government spending and 3. 



## Describe the data

- Source with citation ->
- Data structure / size ->
- Observational unit -> individuals
- Types of variables ->
- Confidentiality/privacy concerns -> Individual information may be unintentionally released. Non-associated people may be acurately or inaccurately labeled as chronically homeless

##Vision for deliverable

- Visualizations ->
- Models -> build a model to see if someone will remain homeless
- Data ->
- Format -> Prefer Shiny, last resort White paper.
  - White paper (Rmd document)
  - Software (R package)
  - Website (Shiny App) (edited